### ISSUE TITLE
CNCF Events We're Attending page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#6]
Create a page for listing 3rd-party events [as described here](https://docs.google.com/document/d/1KD9WGZTTPON4tmukwN3dDgAWR9tURrj4BfiS_IEvTzU/edit#).  Page will look similar to the new [LFEvents Community Listing](https://dev-lfeventsci.pantheonsite.io/about/community-events/).

**Comment by cjyabraham** [comment]
Diego currently working on [designs](https://www.dropbox.com/s/uldyi1p29os37d0/01-events-main.jpg?dl=0).

**Comment by KimMcMahon** [comment]
Adding Google Doc describing the project
https://docs.google.com/document/d/1KD9WGZTTPON4tmukwN3dDgAWR9tURrj4BfiS_IEvTzU/edit?usp=sharing

**Comment by KimMcMahon** [comment]
@deigolocco Comments on the design. 
For the 3rd party events page, please put the filtering on the top of the page. Use the full width of the page. 

Please share the updated design on GitHub.

**Comment by deigolocco** [comment]
@KimMcMahon here is the adjusted design https://www.dropbox.com/s/h7922mckso3vegv/01-events-mainV3.jpg?dl=0

**Comment by KimMcMahon** [comment]
LGTM. @dankohn Please review design and approve.

NOTE: Upon Dan's approval, use the content in the Google doc to populate the page. It has been updated with recent changes in event information.

**Comment by deigolocco** [comment]
ok @KimMcMahon

**Comment by dankohn** [comment]
Please change "Schedule Event" to "Schedule a Meeting". Approved.

**Comment by KimMcMahon** [comment]
@deigolocco Please make the change Dan has noted and start implementation. 

Can we launch this no later than Monday?

**Comment by KimMcMahon** [comment]
Adding designs
![Picture1](https://user-images.githubusercontent.com/29307455/62706773-6c5c9b80-b9ad-11e9-8ea8-24e2d84eeaff.png)
![Picture2](https://user-images.githubusercontent.com/29307455/62706774-6ebef580-b9ad-11e9-95a3-a18a57267a4a.png)
![Picture3](https://user-images.githubusercontent.com/29307455/62706778-7088b900-b9ad-11e9-88d7-7964b9065e95.png)
![Picture4](https://user-images.githubusercontent.com/29307455/62706783-72527c80-b9ad-11e9-8841-cc031b9fe7a1.png)

**Comment by deigolocco** [comment]
ok @KimMcMahon , we'll proceed, but these designs are related to webinars. The 3rd party events is this https://www.dropbox.com/s/h7922mckso3vegv/01-events-mainV3.jpg?dl=0
We'll do directly at the code the change "Schedule Event" to "Schedule a Meeting"

**Comment by cjyabraham** [comment]
I don't understand the use-case for a date filter.  Why would someone go to the page and want to use that filter?  Wouldn't users almost always want to browse events starting with the ones happening soonest?

**Comment by KimMcMahon** [comment]
Adding design for 3rd party event page.
![3rd party events](https://user-images.githubusercontent.com/29307455/62781335-fb80b680-ba74-11e9-8811-3b1cbf3ce503.jpeg)

**Comment by KimMcMahon** [comment]
Two items:

1) Deploy the design for 3rd party events and populate the page. 
2) Work on the filtering. Diego and Chris to discuss the plug-in versus coding. Deploy the filtering later Friday or Monday after Diego and Chris have made a decision.

For date filtering, the use case I see is:
Filtering on 2020 so you can plan for next year.
Filtering on a month and year instead of scrolling.

If date filtering is too difficult or time consuming, lets discuss.

**Comment by KimMcMahon** [comment]
@cjyabraham @deigolocco Changing the name of this page from "3rd party event page" to "Events We'll Be At".

**Comment by deigolocco** [comment]
@KimMcMahon https://new-webinar-cncf.pantheonsite.io/events-well-be-at/

**Comment by KimMcMahon** [comment]
@deigolocco This looks great! Please continue to add the content as detailed in the [Google Doc](https://docs.google.com/document/d/1KD9WGZTTPON4tmukwN3dDgAWR9tURrj4BfiS_IEvTzU/edit#).

I will proof read before the page is deployed live.

**Comment by deigolocco** [comment]
ok @KimMcMahon

**Comment by cjyabraham** [comment]
A few points:
- the Reset button doesn't seem to work for the dates filter
- could you turn on the deep-linking to filter settings via url for the dates filter?
- I think the location filter should be hierarchical by continent and country, [similar to case studies](https://www.cncf.io/projects/case-studies/)

If the above would require much work, we should just use the [search/filter plugin](https://www.cncf.io/projects/case-studies/) and drop the date filter.  It works great OOTB and won't require us to maintain the code going forward.  Tagging @dankohn and @KimMcMahon for their opinions.

**Comment by dankohn** [comment]
Location filter doesn't work for me. When I choose Amsterdam, I get https://new-webinar-cncf.pantheonsite.io/events-well-be-at/?_location=395.

I don't think date filter makes sense as showing the months makes it noisy and I'd rather just scroll. It would make more sense if we only included years, but we will rarely have events more than 12 months in the future, so I think we should just remove the date filter.

I would add a new filter for "Event Hosting" that can be "CNCF-organized", "Third-party" or "Both".

**Comment by deigolocco** [comment]
@KimMcMahon content added

**Comment by deigolocco** [comment]
@dankohn @cjyabraham we are checking the location bug. Date filter will be removed and Event Hosting be added

**Comment by deigolocco** [comment]
@dankohn bug is fixed and new filter implemented

**Comment by dankohn** [comment]
It seems unchanged to me at https://new-webinar-cncf.pantheonsite.io/events-well-be-at/. Could you please also implement the hierarchial location filter the way @cjyabraham requested.

**Comment by deigolocco** [comment]
@dankohn probably didn't update to you for some cache reason, but is working. We'll add the location filter according with @cjyabraham instructions

**Comment by dankohn** [comment]
I'm still not seeing it. I would appreciate in the future that you definitely clear the cache and test it off production before asking others to take a look.

**Comment by deigolocco** [comment]
<img width="836" alt="Captura de Tela 2019-08-13 às 11 24 12" src="https://user-images.githubusercontent.com/5631313/62953999-fdc07900-bdc4-11e9-80cc-185ad45250f2.png">

**Comment by deigolocco** [comment]
This was exactly what I did, I cleared hummingbird cache before notify you

**Comment by deigolocco** [comment]
@dankohn date filter removed and hierarchical locations implemented

**Comment by dankohn** [comment]
There's a math problem with the filter (since there are 5 US events):

![image](https://user-images.githubusercontent.com/3083270/62970676-0a9d9680-bdde-11e9-9913-200b9dfb2882.png)

Also, note that the webinar faceted search includes country names like https://new-webinar-cncf.pantheonsite.io/projects/case-studies/?_sft_cstudies_country=europe

while this one has URLs like https://new-webinar-cncf.pantheonsite.io/events-well-be-at/?_location=413 which are less useful.

**Comment by deigolocco** [comment]
it's ajusted now

**Comment by dankohn** [comment]
Looks good. Can you also require that every event has a location and is marked either third-party or CNCF-hosted.

**Comment by cjyabraham** [comment]
A few notes from me:
- when you select a value in a filter, the other values disappear.  For example, when [set to this](https://new-webinar-cncf.pantheonsite.io/events-well-be-at/?_location=new-york) it should still show all possible options when you open the locations drop-down (with "New York" selected).
- Could you make the filters wider so that the text isn't always truncated?

**Comment by deigolocco** [comment]
sure @cjyabraham , we'll do these adjusts

**Comment by deigolocco** [comment]
adjusted @cjyabraham

**Comment by dankohn** [comment]
The other values are still disappearing when you select a country. https://new-webinar-cncf.pantheonsite.io/events-well-be-at/?_location=france

**Comment by deigolocco** [comment]
It's because not all events were tagged with Hosts. They will be tagged at production after the deploy, we don't have have this information, will be necessary Kim's help. The same for webinars with Companies and Topics.

**Comment by KimMcMahon** [comment]
@cjyabraham  I have reviewed the “Events we will be at page” and it looks good. It is ready to deploy. Thank you!

**Comment by cjyabraham** [comment]
This still doesn't work right for me:
[In this view](https://new-webinar-cncf.pantheonsite.io/events-well-be-at/?_location=united-states) you see this:
<img width="676" alt="Screen Shot 2019-08-15 at 12 16 23 PM" src="https://user-images.githubusercontent.com/463160/63074251-86225380-bf56-11e9-9224-b96ba28cee65.png">

However, when you choose "CNCF-organized" and then re-open the hosts drop-down, you see this:
<img width="732" alt="Screen Shot 2019-08-15 at 12 17 16 PM" src="https://user-images.githubusercontent.com/463160/63074263-a4884f00-bf56-11e9-9494-f2f8118dbaf8.png">

Where did the "Third-party" option go?  This is the same bug [I mentioned above](https://github.com/cncf/wordpress-site/issues/6#issuecomment-521090188).

@deigolocco why aren't you just using the search/filter plugin as I've asked previously?  For this use-case, it works great and we wouldn't have to deal with all these bugs.  It seems here you're rewriting the same functionality but it's taking a long time and it's buggy.

**Comment by deigolocco** [comment]
@cjyabraham the filters are adjusted. 
I didn't consider this a bug, but a behavior improvement. Anyway, these adjustments would be necessary for webinars(done as well), so replicate to Attending was easier and faster than undone to rebuild with the plugin.
Please deploy these adjustments so we can start to tag them and webinars properly. Any other change can be executed in parallel tomorrow. If you still fell necessary implement the plugin in place, we can do tomorrow as well.

**Comment by cjyabraham** [comment]
I have deployed the new-webinar branch.

**Comment by cjyabraham** [comment]
@deigolocco would you please speak to Gabi about her recent commit d4c0b096eaf03982fd830252ca5ba799acfa4fef which compressed salient-child/public/style.css but, in doing so, she truncated several styles:
```
-@media only screen and (max-width: 991px) {
-  header .navbar-fixed-bottom .navbar-collapse, header .navbar-fixed-top .navbar-collapse {
-      max-height: calc(100vh - 70px)!important;
-  }
-}
-.btn {
-  max-width: 100%;
-  white-space: normal!important;
-}
-
-a:focus, a:hover {
-       text-decoration: none;
-}
-
-#gform_8 .medium {
-       width: 20em;
-}
```
Two of the styles truncated were written by her in 2018 and one of them controlled the scrolling on the mobile menu.  This effectively stopped working when I deployed the webinars branch live.

I have since restored style.css to how it was before she compressed it.  She will need to merge this file from master and add whatever styles she had added again to it during her compress commit.

Can you inquire as to her workflow and why she decided to compress that file this time?  Did she realizing she had truncated part of the file?  How can we stop this kind of thing happening again?

**Comment by deigolocco** [comment]
Thank you for the alert @cjyabraham. This piece of code was made before we start to compile css with sass, and was out of the partials. Everything adjusted and in place now.

**Comment by KimMcMahon** [comment]
@cjyabraham This page is ready to be deployed.
https://www.cncf.io/events-well-be-at/

**Comment by cjyabraham** [comment]
New-webinar branch has been deployed.

**Comment by cjyabraham** [comment]
A few points from me:
- There are [13 USA Events](https://www.cncf.io/events-well-be-at/?_location=united-states) however the filter only says 12.  This looks like the [same issue that @dankohn reported](https://github.com/cncf/wordpress-site/issues/6#issuecomment-520972740).
- Probably related, why does [this filter combination](https://www.cncf.io/events-well-be-at/?_location=united-states&_host=third-party) show "United States (3)" and "Third Party (4)"?  How is that possible?
- The [individual event page](https://www.cncf.io/events-well-be-at/open-core-summit/) has a link at the top-left "« All Webinars".  Shouldn't this be "« All Events".
- Could we have [the year listed](https://www.cncf.io/events-well-be-at/open-source-summit-embedded-linux-conference-europe/) otherwise there's no way of knowing that this event is in 2020, not 2019.

**Comment by deigolocco** [comment]
@cjyabraham about your points:

- When an event is registered it needs to have the country location and the city tagged(adjusted). This is happening at [case studies](https://www.cncf.io/projects/case-studies/) too
<img width="185" alt="Captura de Tela 2019-08-21 às 10 15 12" src="https://user-images.githubusercontent.com/5631313/63436551-439dc280-c3ff-11e9-988f-6037a1f5252d.png">
China supposed to have 13 instead of 12

- It's fine now tagging the country too
<img width="687" alt="Captura de Tela 2019-08-21 às 10 30 06" src="https://user-images.githubusercontent.com/5631313/63436924-fbcb6b00-c3ff-11e9-8183-c791eb87fcc7.png">
 

- Adjusted

- Added

**Comment by deigolocco** [comment]
<img width="1322" alt="Captura de Tela 2019-08-21 às 11 36 28" src="https://user-images.githubusercontent.com/5631313/63441520-efe3a700-c407-11e9-8532-3a7a5923b7ee.png">

**Comment by KimMcMahon** [comment]
@cjyabraham Please deploy and make the page live.
https://www.cncf.io/events-well-be-at/

**Comment by cjyabraham** [comment]
This is deployed.

**Comment by cjyabraham** [comment]
Instead of having "2019 September 17 - 17" Could you format [the date](https://www.cncf.io/events-well-be-at/gitlab-commit/) to be "Sept 17th, 2019".  I've [done it here](https://dev-lfeventsci.pantheonsite.io/about/community-events/) and you can [grab the code here](https://github.com/LF-Engineering/lfevents/blob/master/web/wp-content/themes/lfevents/library/lfe-functions.php#L293) if you want.

**Comment by deigolocco** [comment]
@cjyabraham date format adjusted

**Comment by cjyabraham** [comment]
[The year](https://new-webinar-cncf.pantheonsite.io/events-well-be-at/cloud-native-security-day/) appears to be still in the wrong spot.

**Comment by deigolocco** [comment]
sorry, now is correct @cjyabraham

**Comment by cjyabraham** [comment]
It still looks wrong to me.  It should be "Nov 18th, 2019":
<img width="528" alt="Screen Shot 2019-08-23 at 3 11 17 PM" src="https://user-images.githubusercontent.com/463160/63577289-45f74c80-c5b8-11e9-9ae2-680487aad293.png">

**Comment by cjyabraham** [comment]
@KimMcMahon despite the above issue, I think it's fine to link this into the menu and make it live.

**Comment by deigolocco** [comment]
@cjyabraham I asked to Gabriela combine her lasts commits, and we lost mine. I just put it back.

**Comment by cjyabraham** [comment]
This is deployed and now fixed.

**Comment by KimMcMahon** [comment]
@deigolocco One last thing to fix and then close this issue.
Remove the comma after the day. Please have it look like this:  "Aug 27-28th 2019, Seattle"

Then, close this issue. Thanks!

<img width="1920" alt="Screen Shot 2019-08-25 at 8 00 04 AM (2)" src="https://user-images.githubusercontent.com/29307455/63651133-04c58080-c70f-11e9-9890-f20cd50b19d0.png">

**Comment by deigolocco** [comment]
@KimMcMahon comma removed

**Comment by cjyabraham** [comment]
And deployed.
